import json
import os
import random
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

load_dotenv()

RAW_DIR = "data/raw"
PROCESSED_DIR = "data/processed"

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=os.getenv("SPOTIFY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIFY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIFY_REDIRECT_URI"),
    scope="user-read-private user-read-email user-top-read user-read-recently-played "
          "user-library-read playlist-read-private playlist-modify-private playlist-modify-public"
))

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def get_rediscovery_track_ids(count=10):
    """Top N track IDs from Day 3's rediscovery scores."""
    data = load_json(os.path.join(PROCESSED_DIR, "rediscovery_scores.json"))
    return [song["track_id"] for song in data[:count]]

def find_track_for_artist(artist_name, raw_dir=RAW_DIR):
    """
    Adjacent Artists only gives us artist names, not track IDs.
    Search our own raw data for a real track by that artist.
    """
    files = ["top_tracks_short_term.json", "top_tracks_medium_term.json",
             "top_tracks_long_term.json", "recently_played.json"]
    for filename in files:
        items = load_json(os.path.join(raw_dir, filename))
        for item in items:
            track = item.get("track", item)
            if track.get("artists") and track["artists"][0]["name"] == artist_name:
                return track.get("id")
    return None

def get_adjacent_track_ids(count=10):
    """Top N adjacent artists -> resolve to a real track ID each."""
    data = load_json(os.path.join(PROCESSED_DIR, "bubble_analysis.json"))
    adjacent_artists = data["adjacent_artists"][:count * 2]  # buffer in case some don't resolve

    track_ids = []
    for artist in adjacent_artists:
        tid = find_track_for_artist(artist["artist_name"])
        if tid and tid not in track_ids:
            track_ids.append(tid)
        if len(track_ids) >= count:
            break
    return track_ids

def build_playlist_tracks(rediscovery_count=10, adjacent_count=10):
    rediscovery_ids = get_rediscovery_track_ids(rediscovery_count)
    adjacent_ids = get_adjacent_track_ids(adjacent_count)

    all_ids = rediscovery_ids + adjacent_ids
    random.shuffle(all_ids)

    print(f"Rediscovery tracks found: {len(rediscovery_ids)}")
    print(f"Adjacent tracks found: {len(adjacent_ids)}")
    print(f"Total playlist tracks: {len(all_ids)}")

    return all_ids

def create_spotify_playlist(track_ids, name, description):
    """
    Spotify removed POST /users/{user_id}/playlists in the Feb 2026 API migration.
    The replacement is POST /me/playlists (current user only — no user_id needed).
    spotipy's built-in user_playlist_create() still targets the old removed endpoint,
    so we call the new one directly via spotipy's internal _post helper.
    """
    payload = {
        "name": name,
        "public": False,
        "description": description
    }
    playlist = sp._post("me/playlists", payload=payload)

    track_uris = [f"spotify:track:{tid}" for tid in track_ids]
    # Spotify renamed POST /playlists/{id}/tracks to POST /playlists/{id}/items
    # in the Feb 2026 migration. spotipy's playlist_add_items() still targets the
    # old removed path, so we call the new one directly.
    sp._post(f"playlists/{playlist['id']}/items", payload={"uris": track_uris})

    return playlist

def main():
    from datetime import date

    track_ids = build_playlist_tracks(rediscovery_count=10, adjacent_count=10)

    if not track_ids:
        print("No tracks found — make sure spotify_memory.py and music_bubble.py have been run.")
        return

    playlist_name = f"Rediscovery Mix — {date.today().isoformat()}"
    description = ("Auto-generated by Music Intelligence System: half forgotten favorites "
                    "you used to love, half artists just outside your usual bubble.")

    playlist = create_spotify_playlist(track_ids, playlist_name, description)

    print(f"\nPlaylist created: {playlist['name']}")
    print(f"Open it here: {playlist['external_urls']['spotify']}")

if __name__ == "__main__":
    main()